sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tGCDgVmnwj9rM4paTS6
    access-key-secret: hVYKCFiJe0BR70s04D2unmVUQYaMtR
    bucket-name: abel-oss-study
